// AUTHENTICATION ACTIONS
export const CURRENT_USER_LOADED = 'CURRENT_USER_LOADED';
export const JWT_LOADED = 'JWT_LOADED';
export const REMOVE_JWT = 'REMOVE_JWT';

// USERS ACTIONS
export const USERS_LOADED = 'USERS_LOADED';

// POSTS ACTIONS
export const POSTS_LOADED = 'POSTS_LOADED';
export const POST_LOADED = 'POST_LOADED';

// ADMIN ACTIONS
export const ADMIN_COUNT_LOADED = 'ADMIN_COUNT_LOADED';

// ADMIN PAGES ACTIONS
export const RECORDS_LOADED = 'RECORDS_LOADED';
export const RECORD_ADDED = 'RECORD_ADDED';
export const RECORD_EDITED = 'RECORD_EDITED';
export const RECORD_DELETED = 'RECORD_DELETED';
export const COMMENT_VISIBILITY_CHANGED = 'COMMENT_VISIBILITY_CHANGED';
export const SORT_DATA = 'SORT_DATA';
export const CHANGE_PAGE_NUMBER = 'CHANGE_PAGE_NUMBER';
export const CHANGE_PAGE_LENGTH = 'CHANGE_PAGE_LENGTH';
export const CHANGE_SELECTED_RECORD = 'CHANGE_SELECTED_RECORD';
export const CHANGE_ADMIN_OPERATION = 'CHANGE_ADMIN_OPERATION';
export const LOAD_FORM_DATA = 'LOAD_FORM_DATA';
export const FILTER_ADMIN_DATA = 'FILTER_ADMIN_DATA';
export const RESET_ADDED_RECORD = 'RESET_ADDED_RECORD';
export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
export const RESET_STATE = 'RESET_STATE';

// COMMENTS ACTIONS
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_DELETED = 'COMMENT_DELETED';

// PRACTICE AREAS ACTIONS
export const PRACTICE_AREAS_LOADED = 'PRACTICE_AREAS_LOADED';
export const CHANGE_PRACTICE_AREA = 'CHANGE_PRACTICE_AREA';

// PRACTICE AREA ACTIONS
export const PRACTICE_AREA_LOADED = 'PRACTICE_AREA_LOADED';

// MATTERS ACTIONS
export const MATTERS_LOADED = 'MATTERS_LOADED';
export const MATTER_ADDED = 'MATTER_ADDED';
export const MATTER_EDITED = 'MATTER_EDITED';

// STAFF ACTIONS
export const STAFF_LOADED = 'STAFF_LOADED';
export const STAFF_USERS_LOADED = 'STAFF_USERS_LOADED';
export const STAFF_ADDED = 'STAFF_ADDED';
export const STAFF_USER_ADDED = 'STAFF_USER_ADDED';
export const STAFF_EDITED = 'STAFF_EDITED';
export const STAFF_USER_EDITED = 'STAFF_USER_EDITED';

// CLIENT ACTIONS
export const CLIENTS_LOADED = 'CLIENTS_LOADED';
export const CLIENT_USERS_LOADED = 'CLIENT_USERS_LOADED';
export const CLIENT_ADDED = 'CLIENT_ADDED';
export const CLIENT_USER_ADDED = 'CLIENT_USER_ADDED';
export const CLIENT_EDITED = 'CLIENT_EDITED';
export const CLIENT_USER_EDITED = 'CLIENT_USER_EDITED';

// BLOG HOME ACTIONS
export const SHOW_ALL_POSTS = 'SHOW_ALL_POSTS';
export const SORT_POSTS = 'SORT_POSTS';
export const FILTER_BY_AREA = 'FILTER_BY_AREA';
export const FILTER_BY_AUTHOR = 'FILTER_BY_AUTHOR';
export const FILTER_POSTS_BY_KEYWORD = 'FILTER_BY_KEYWORD';
export const LOAD_MORE = 'LOAD_MORE';
